# Generated by Django 5.0.2 on 2024-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image", models.ImageField(upload_to="product/")),
            ],
        ),
    ]
