# Generated by Django 5.0.2 on 2024-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
