# Generated by Django 5.0.2 on 2024-02-17 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0003_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="product_description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="product_name",
        ),
    ]
