# Generated by Django 5.0.2 on 2024-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="static/images/"),
        ),
    ]
