# Generated by Django 5.0.2 on 2024-02-17 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myweb", "0006_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
